apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod-cluster
description: prod cluster
requireApproval: true
gke:
 cluster: projects/software-delivery-demo/locations/us-central1-b/clusters/prod-cluster
